name: Build competitor feed (FR)

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 */6 * * *"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run harvester (FR)
        run: |
          mkdir -p data/cbdf
          python fr/stealth_competitor_feed.py \
            --domain "https://www.cbd.fr" \
            --out-json "data/cbdf/cbd_competitor.json" \
            --out-rss  "data/cbdf/cbd_competitor.rss"

      - name: Commit changes (if any)
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config --global safe.directory "$GITHUB_WORKSPACE"
            git config user.name  "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add data/cbdf/cbd_competitor.json data/cbdf/cbd_competitor.rss || true
            git commit -m "Update competitor feed (FR)" || true
            git pull --rebase --autostash || true
            git push || true
          else
            echo "No changes to commit"
          fi
