name: Build competitor pages (PT)

on:
  workflow_dispatch: {}
  workflow_run:
    workflows: ["Build competitor feed (PT)"]
    types: [completed]

permissions:
  contents: write

jobs:
  build:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade requests

      - name: Generate PT pages
        run: |
          mkdir -p scripts
          # Assure que le script existe (si tu viens de le créer, pas besoin de cette ligne)
          # python -c "open('scripts/pt_generate_pages.py').close()"
          python scripts/pt_generate_pages.py

      - name: Commit changes (if any)
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name  "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add pt/novidades/**/*.html pt/novidades/*.html || true
            git commit -m "Gerar páginas de novidades (PT) a partir dos concorrentes"
            git pull --rebase
            git push
          else
            echo "No changes to commit"
          fi
